### ISSUE TITLE
Tests under `abstract` class are not run

### ISSUE THREAD

**Issue by algomaster99** [algomaster99/collector-sahab#112]
The tests [here](https://github.com/JMRI/JMRI/commit/d7c66f67a788a3e619819bdaa26fd950a7a0bd7f) are not run. It seems that our JUnit runner does not discover them.

```
╷
├─ JUnit Jupiter ✔
├─ JUnit Vintage ✔
├─ JUnit Platform Suite ✔
└─ ArchUnit JUnit 5 ✔

Test run finished after 54 ms
[         4 containers found      ]
[         0 containers skipped    ]
[         4 containers started    ]
[         0 containers aborted    ]
[         4 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

```

**Comment by monperrus** [comment]
Perhaps because the class name does not start or end with Test, which is the surefire convention, 
see 
https://github.com/INRIA/spoon/blob/master/src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java#L249

**Comment by algomaster99** [comment]
That is a good idea. Probably JUnit test discoverer also enforces it. Thank you!

**Comment by algomaster99** [comment]
@monperrus

The following is written under JUnit Jupiter concepts.
> Test Class

>    any top-level class, static member class, or [@Nested class](https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested) that contains at least one test method, i.e. a container. Test classes must not be **abstract** and must have a single constructor.

Reference: https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher

I will add a test case for this in our tool.
