### ISSUE TITLE
Empty output is generated

### ISSUE THREAD

**Issue by khaes-kth** [algomaster99/collector-sahab#2]
When I run the debugger for the [commons-math-core](https://github.com/apache/commons-math/tree/master/commons-math-core) module of [commons-math](https://github.com/apache/commons-math), I get an empty output.

**Comment by algomaster99** [comment]
Looking into it.

**Comment by algomaster99** [comment]
It was happening because the breakpoint was never reached.

**Comment by khaes-kth** [comment]
thanks for the clarification @algomaster99 !
