### ISSUE TITLE
Incorrect classpath generated for multi-module maven projects

### ISSUE THREAD

**Issue by khaes-kth** [algomaster99/collector-sahab#3]
The command in the readme file does not generate the correct classpath for maven projects with multiple modules, such as [commons-math](https://github.com/apache/commons-math). To include all the dependencies in the classpath, same command should also be run in submodule folders.

**Comment by algomaster99** [comment]
The process of automating the generation of classpath is a bit difficult given the number of ways it can be done and different developers have different opinions about it. For now, I have described the manual process [here](https://github.com/algomaster99/collector-sahab#setup-project-for-collecting-runtime-statistics).

**Comment by khaes-kth** [comment]
Thanks @algomaster99
