### ISSUE TITLE
Report is not generated (experiment 2)

### ISSUE THREAD

**Issue by algomaster99** [algomaster99/collector-sahab#83]
The second run of the experiment, with `execution-depth=0`, threw an exception for the following commits because of which the report was not generated.

| Commit  | Reason/Resolution  |
|---|---|
| [0a8a5d1d5fc3a6d0681e7344ddd773acdea27dda](https://github.com/khaes-kth/drr-execdiff/commit/0a8a5d1d5fc3a6d0681e7344ddd773acdea27dda)  | https://github.com/GumTreeDiff/gumtree/issues/285  |
| [3ae853a6464baa3dd498a43e2af9638f8ba09d86](https://github.com/khaes-kth/drr-execdiff/commit/3ae853a6464baa3dd498a43e2af9638f8ba09d86)  | https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/249 |
| [5db7253811426931ad8b303027542106bbe756e5](https://github.com/khaes-kth/drr-execdiff/commit/5db7253811426931ad8b303027542106bbe756e5)  | Terminated before the process was finished. Threw memory exception when ran on local without time limits.  |
| [6043bd63b93ee4565b6ef3efe0179fbb2351b9c3](https://github.com/khaes-kth/drr-execdiff/commit/6043bd63b93ee4565b6ef3efe0179fbb2351b9c3)  | Input files not generated. Multi method change so GumTree could not find method.  https://github.com/GumTreeDiff/gumtree/issues/285   |
| [737913664e57dad4768ff538a81ace8e0f0db559](https://github.com/khaes-kth/drr-execdiff/commit/737913664e57dad4768ff538a81ace8e0f0db559)  | https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/249  |
| [a16399f50f84d3d82d6bb0306996961b2a82bb06](https://github.com/khaes-kth/drr-execdiff/commit/a16399f50f84d3d82d6bb0306996961b2a82bb06)  |  Report is generated. Path: `/mnt/hdd2/khesoem/exec-diff0/output/sahab-reports/a16399f50f84d3d82d6bb0306996961b2a82bb06/left.json`, `/mnt/hdd2/khesoem/exec-diff0/output/sahab-reports/a16399f50f84d3d82d6bb0306996961b2a82bb06/right.json`. `Infinity` is not being parsed by state diff computer. https://github.com/khaes-kth/PatchExplainer/issues/3 |
| [d5f817b6b3e6f63e542787f741b4ec8cb62a7662](https://github.com/khaes-kth/drr-execdiff/commit/d5f817b6b3e6f63e542787f741b4ec8cb62a7662)  | https://github.com/GumTreeDiff/gumtree/issues/285  |
| [e707bbcc114bb0afa096454f9a57ff08323a5de8](https://github.com/khaes-kth/drr-execdiff/commit/e707bbcc114bb0afa096454f9a57ff08323a5de8)  | Terminated before the process was finished. Takes around 5 hours.  |

### sahab-left.json does not exist

| Commit  | Reason/Resolution  |
|---|---|
| [5b45b78464d5888ba60a3325f5ccc12876582cca](https://github.com/khaes-kth/drr-execdiff/commit/5b45b78464d5888ba60a3325f5ccc12876582cca)  | Input files not generated. GumTree could not find method. |
| [21dba3d0e53f1b2d8452aca3f760d418ff470cdc](https://github.com/khaes-kth/drr-execdiff/commit/21dba3d0e53f1b2d8452aca3f760d418ff470cdc)  | Input files not generated. GumTree could not find method. |
| [6bf70cd6214303b773d2091b60e93ed0a52caea1](https://github.com/khaes-kth/drr-execdiff/commit/6bf70cd6214303b773d2091b60e93ed0a52caea1) | Input files not generated. GumTree could not find method. |
| [fbf87fd5c93e46b28c3987e16b05f1d1da0b021d](https://github.com/khaes-kth/drr-execdiff/commit/fbf87fd5c93e46b28c3987e16b05f1d1da0b021d) | Input files not generated. GumTree could not find method. |

### sahab-right.json does not exist

| Commit  | Reason/Resolution  |
|---|---|
| [5f99f45853b5c98bff5dbcbfeac837aa2c686d8c](https://github.com/khaes-kth/drr-execdiff/commit/5f99f45853b5c98bff5dbcbfeac837aa2c686d8c)  | Terminated before process finished. |
| [a8ad6b9853609e86cbf9534fff05377dfdf7790a](https://github.com/khaes-kth/drr-execdiff/commit/a8ad6b9853609e86cbf9534fff05377dfdf7790a) | Terminated before process finished. |
| [6e9e91677774089db6e6b9de2945716269216327](https://github.com/khaes-kth/drr-execdiff/commit/6e9e91677774089db6e6b9de2945716269216327) | Terminated before process finished. |
| [047ef2fcc23f713dc2e682d8b4f2ca5f994bb7ca](https://github.com/khaes-kth/drr-execdiff/commit/047ef2fcc23f713dc2e682d8b4f2ca5f994bb7ca) | Terminated before process finished. |
| [37757413c6d69946ea68c27c12ac0f7fd38b535c](https://github.com/khaes-kth/drr-execdiff/commit/37757413c6d69946ea68c27c12ac0f7fd38b535c) | Terminated before process finished. |

### Entire commit folder does not exist

| Commit  | Reason/Resolution  | 
|---|---|
| [af19a3800c20db42db18bc3ac51ce90236ca9517](https://github.com/khaes-kth/drr-execdiff/commit/af19a3800c20db42db18bc3ac51ce90236ca9517) | Math-105 is not a maven project |
| [885bbd7d0f6db843627986bf97d3f0db4cfddb02](https://github.com/khaes-kth/drr-execdiff/commit/885bbd7d0f6db843627986bf97d3f0db4cfddb02) | Math-105 is not a maven project |

### Report exists but there are no states in left

| Commit  | Reason/Resolution  | 
|---|---|
| [30709758f0b33338fa697b400112fac836e4cef1](https://github.com/khaes-kth/drr-execdiff/commit/30709758f0b33338fa697b400112fac836e4cef1) | No breakpoints or methods were encountered. @khaes-kth DIFF HTML is not generated. Sahab is reporting the states correctly. Left threw an `NPE`. |
| [98dc9eef38a8a3353d110786ffed93ec83d1cc02](https://github.com/khaes-kth/drr-execdiff/commit/98dc9eef38a8a3353d110786ffed93ec83d1cc02) | No breakpoints or methods were encountered. |
| [fcadcfa2001ad4a86718e6a98856b332d37a4825](https://github.com/khaes-kth/drr-execdiff/commit/fcadcfa2001ad4a86718e6a98856b3) | No breakpoints or methods were encountered. |
| [36ceb2ae32c903057a1f574e1e8963c3f26a5a2f](https://github.com/khaes-kth/drr-execdiff/commit/36ceb2ae32c903057a1f574e1e8963c3f26a5a2f) | No breakpoints or methods were encountered. |
| [3177794e4cd6e9d09813d5e0c750c0cac5bc3da7](https://github.com/khaes-kth/drr-execdiff/commit/3177794e4cd6e9d09813d5e0c750c0cac5bc3da7) | No breakpoints or methods were encountered. |

### Report exists but there are no states in right

| Commit  | Reason/Resolution  | 
|---|---|
| [98dc9eef38a8a3353d110786ffed93ec83d1cc02](https://github.com/khaes-kth/drr-execdiff/commit/98dc9eef38a8a3353d110786ffed93ec83d1cc02) | No breakpoints or methods were encountered. |
| [fcadcfa2001ad4a86718e6a98856b332d37a4825](https://github.com/khaes-kth/drr-execdiff/commit/fcadcfa2001ad4a86718e6a98856b3) | No breakpoints or methods were encountered. |
| [92430cd021f1afc55f40d99090893eddd620ed9b](https://github.com/khaes-kth/drr-execdiff/commit/92430cd021f1afc55f40d99090893eddd620ed9b) | No breakpoints or methods were encountered. |
| [5f57bcfae6e6bebc98de9d9b49d01e6240b63554](https://github.com/khaes-kth/drr-execdiff/commit/5f57bcfae6e6bebc98de9d9b49d01e6240b63554) | No breakpoints or methods were encountered. |
| [1482e9e4fba71651f86299f5abd0688af176e3db](https://github.com/khaes-kth/drr-execdiff/commit/1482e9e4fba71651f86299f5abd0688af176e3db) |  No breakpoints or methods were encountered. |

**Comment by algomaster99** [comment]
### APPROPRIATE COMMITS: sahab doesnt find target

- https://github.com/google/gson/commit/b1fb9ca9a1bea5440bc6a5b506ccf67236b08243: `MatchedLineFinder` fails to find the class file. Reference: https://github.com/khaes-kth/drr-execdiff/blob/master/dspot-sdiffs/notes.txt#L100.
- https://github.com/google/gson/commit/74e37110e5edf38d1c9ec1b46f42670340a0c6c7: `extras` is not compiled. Reference: https://github.com/khaes-kth/drr-execdiff/blob/d3ca7200d8460db15c3dd2deb4f8554809eeda87/dspot-sdiffs/notes.txt#L101
- https://github.com/google/gson/commit/ada597e69a78b8b99f79f79493cbf51e16045202: works. Left version is not generated because tests do not exist for the first left. Reference: https://github.com/khaes-kth/drr-execdiff/blob/d3ca7200d8460db15c3dd2deb4f8554809eeda87/dspot-sdiffs/notes.txt#L102
- https://github.com/google/gson/commit/9a2421997e83ec803c88ea370a2d102052699d3b: works. Left version is not generated because tests do not exist for the first left. Reference: https://github.com/khaes-kth/drr-execdiff/blob/d3ca7200d8460db15c3dd2deb4f8554809eeda87/dspot-sdiffs/notes.txt#L103
- https://github.com/google/gson/commit/9e6f2bab20257b6823a5b753739f047d79e9dcbd: works. Left version is not generated because tests do not exist for the first left. Reference: https://github.com/khaes-kth/drr-execdiff/blob/d3ca7200d8460db15c3dd2deb4f8554809eeda87/dspot-sdiffs/notes.txt#L104
- https://github.com/google/gson/commit/44cad04a639b3a53f4205f93acda37b3f7d10871: works. Left version is not generated because tests do not exist for the first left. Reference: https://github.com/khaes-kth/drr-execdiff/blob/d3ca7200d8460db15c3dd2deb4f8554809eeda87/dspot-sdiffs/notes.txt#L105

**Comment by khaes-kth** [comment]
Thanks!

**Comment by algomaster99** [comment]
@khaes-kth I have revised the `MatchedLineFinder` according to what we discussed. All the tests are passing, but I am sure I need to revise this report again. I will open another issue to see if the failed patches pass now.
