### ISSUE TITLE
Experiment analysis after rewriting (but not running) MLF

### ISSUE THREAD

**Issue by algomaster99** [algomaster99/collector-sahab#94]
For `execution-depth=0`,

### Reports with no states (n=13)

| **Commit**                               | **Now fixed?** |
|------------------------------------------|----------------|
| [98dc9eef38a8a3353d110786ffed93ec83d1cc02](https://github.com/khaes-kth/drr-execdiff/commit/98dc9eef38a8a3353d110786ffed93ec83d1cc02) |   YES. Changed `1.3` to `1.6`.             |
| [9f598c25fbf4391891141d21b3005635eb35857f](https://github.com/khaes-kth/drr-execdiff/commit/9f598c25fbf4391891141d21b3005635eb35857f) |  NO. Patch introduces compilation error.              |
| [38b1c6e5763b55870959e6d75a6e5b46cacd382e](https://github.com/khaes-kth/drr-execdiff/commit/38b1c6e5763b55870959e6d75a6e5b46cacd382e) |  NO. Right states are not there because we do not record `throw`.              |
| [30896a1448dbdb0482f4f469b943ffe6e162608b](https://github.com/khaes-kth/drr-execdiff/commit/30896a1448dbdb0482f4f469b943ffe6e162608b) |  NO. Patch introduces compilation error. Missing return statement.              |
| [fcadcfa2001ad4a86718e6a98856b332d37a4825](https://github.com/khaes-kth/drr-execdiff/commit/fcadcfa2001ad4a86718e6a98856b332d37a4825) |  NO. Multiple Hunks are not supported.              |
| [5f57bcfae6e6bebc98de9d9b49d01e6240b63554](https://github.com/khaes-kth/drr-execdiff/commit/5f57bcfae6e6bebc98de9d9b49d01e6240b63554) |  NO. Patch introduces compilation error.              |
| [92430cd021f1afc55f40d99090893eddd620ed9b](https://github.com/khaes-kth/drr-execdiff/commit/92430cd021f1afc55f40d99090893eddd620ed9b) |  NO. Patch introduces compilation error.              |
| [6ae26132188f016d96b87875f419738e597c22ed](https://github.com/khaes-kth/drr-execdiff/commit/6ae26132188f016d96b87875f419738e597c22ed) |  NO. Left states are not there because method is not called.              |
| [30709758f0b33338fa697b400112fac836e4cef1](https://github.com/khaes-kth/drr-execdiff/commit/30709758f0b33338fa697b400112fac836e4cef1) |  NO. Left states are not there because method is not called. (Same as above)              |
| [36ceb2ae32c903057a1f574e1e8963c3f26a5a2f](https://github.com/khaes-kth/drr-execdiff/commit/36ceb2ae32c903057a1f574e1e8963c3f26a5a2f) |  NO. Left states are not there because method is not called. (Same as above)               |
| [1482e9e4fba71651f86299f5abd0688af176e3db](https://github.com/khaes-kth/drr-execdiff/commit/1482e9e4fba71651f86299f5abd0688af176e3db) |  NO. Patch introduces compilation error.               |
| [af6373a9778a4579626928b9eee8a8719398a7e7](https://github.com/khaes-kth/drr-execdiff/commit/af6373a9778a4579626928b9eee8a8719398a7e7) | NO. Left states are not there because method is not called.               |
| [3177794e4cd6e9d09813d5e0c750c0cac5bc3da7](https://github.com/khaes-kth/drr-execdiff/commit/3177794e4cd6e9d09813d5e0c750c0cac5bc3da7) |  NO. Left states are not there because method is not called.              |

### Empty reports (n=22)

| **Commit**                               | **Now fixed?** |
|------------------------------------------|----------------|
| [37757413c6d69946ea68c27c12ac0f7fd38b535c](https://github.com/khaes-kth/drr-execdiff/commit/37757413c6d69946ea68c27c12ac0f7fd38b535c) | NO. Timeout (10000s) reached.               |
| [6043bd63b93ee4565b6ef3efe0179fbb2351b9c3](https://github.com/khaes-kth/drr-execdiff/commit/6043bd63b93ee4565b6ef3efe0179fbb2351b9c3) | NO. Multiple Hunks are not supported.               |
| [137c2eaf54c3c4eb5a428b6c55be1d86d33c5e4e](https://github.com/khaes-kth/drr-execdiff/commit/137c2eaf54c3c4eb5a428b6c55be1d86d33c5e4e) |  NO. Timeout (10000s) reached.               |
| [acf61536ac09406e477a5e900c5f0b0c9691fdf7](https://github.com/khaes-kth/drr-execdiff/commit/acf61536ac09406e477a5e900c5f0b0c9691fdf7) |   NO. Timeout (10000s) reached.             |
| [9a573745a43b4ea1d5ce939d67179ef13da88a4d](https://github.com/khaes-kth/drr-execdiff/commit/9a573745a43b4ea1d5ce939d67179ef13da88a4d) |  NO. Timeout (10000s) reached.               |
| [0077dfd7c6af8559c220c97ef5f073ed8b49af47](https://github.com/khaes-kth/drr-execdiff/commit/0077dfd7c6af8559c220c97ef5f073ed8b49af47) |     NO. Timeout (10000s) reached.            |
| [5f99f45853b5c98bff5dbcbfeac837aa2c686d8c](https://github.com/khaes-kth/drr-execdiff/commit/5f99f45853b5c98bff5dbcbfeac837aa2c686d8c) | NO. Timeout (10000s) reached.                |
| [f4c53b9b7cff5492eb5b58799694a54cf828f6f9](https://github.com/khaes-kth/drr-execdiff/commit/f4c53b9b7cff5492eb5b58799694a54cf828f6f9) |   NO. Timeout (10000s) reached.             |
| [737913664e57dad4768ff538a81ace8e0f0db559](https://github.com/khaes-kth/drr-execdiff/commit/737913664e57dad4768ff538a81ace8e0f0db559) |  YES. (Bug in matching using AST diff)            |
| [d5f817b6b3e6f63e542787f741b4ec8cb62a7662](https://github.com/khaes-kth/drr-execdiff/commit/d5f817b6b3e6f63e542787f741b4ec8cb62a7662) |  NO. Multiple Hunks are not supported.              |
| [047ef2fcc23f713dc2e682d8b4f2ca5f994bb7ca](https://github.com/khaes-kth/drr-execdiff/commit/047ef2fcc23f713dc2e682d8b4f2ca5f994bb7ca) |   NO. Timeout (10000s) reached.             |
| [e707bbcc114bb0afa096454f9a57ff08323a5de8](https://github.com/khaes-kth/drr-execdiff/commit/e707bbcc114bb0afa096454f9a57ff08323a5de8) |   NO. Timeout (10000s) reached.             |
| [6bf70cd6214303b773d2091b60e93ed0a52caea1](https://github.com/khaes-kth/drr-execdiff/commit/6bf70cd6214303b773d2091b60e93ed0a52caea1) |   YES.  (Bug in matching using AST diff)            |
| [21dba3d0e53f1b2d8452aca3f760d418ff470cdc](https://github.com/khaes-kth/drr-execdiff/commit/21dba3d0e53f1b2d8452aca3f760d418ff470cdc) |  YES. (Bug in matching using AST diff)             |
| [a8ad6b9853609e86cbf9534fff05377dfdf7790a](https://github.com/khaes-kth/drr-execdiff/commit/a8ad6b9853609e86cbf9534fff05377dfdf7790a) |    NO. Timeout (10000s) reached.             |
| [6e9e91677774089db6e6b9de2945716269216327](https://github.com/khaes-kth/drr-execdiff/commit/6e9e91677774089db6e6b9de2945716269216327) | NO. Timeout (10000s) reached.                |
| [fbf87fd5c93e46b28c3987e16b05f1d1da0b021d](https://github.com/khaes-kth/drr-execdiff/commit/fbf87fd5c93e46b28c3987e16b05f1d1da0b021d) |   NO. Multiple Hunks are not supported. (Other is import statement)              |
| [3ae853a6464baa3dd498a43e2af9638f8ba09d86](https://github.com/khaes-kth/drr-execdiff/commit/3ae853a6464baa3dd498a43e2af9638f8ba09d86) |   YES. (Bug in matching using AST diff)             |
| [0a8a5d1d5fc3a6d0681e7344ddd773acdea27dda](https://github.com/khaes-kth/drr-execdiff/commit/0a8a5d1d5fc3a6d0681e7344ddd773acdea27dda) |   YES. (Bug in matching using AST diff)             |
| [cc196972d29c2bf393ef85b23518c86a87708716](https://github.com/khaes-kth/drr-execdiff/commit/cc196972d29c2bf393ef85b23518c86a87708716) |    NO. Timeout (10000s) reached.             |
| [5db7253811426931ad8b303027542106bbe756e5](https://github.com/khaes-kth/drr-execdiff/commit/5db7253811426931ad8b303027542106bbe756e5) |  NO. Timeout (10000s) reached.              |
| [5b45b78464d5888ba60a3325f5ccc12876582cca](https://github.com/khaes-kth/drr-execdiff/commit/5b45b78464d5888ba60a3325f5ccc12876582cca) |   YES. (Bug in matching using AST diff)             |

There are two more commits for which report is not generated, but the project which they belong to is not a maven project.
1. [af19a3800c20db42db18bc3ac51ce90236ca9517](https://github.com/khaes-kth/drr-execdiff/commit/af19a3800c20db42db18bc3ac51ce90236ca9517)
2. [885bbd7d0f6db843627986bf97d3f0db4cfddb02](https://github.com/khaes-kth/drr-execdiff/commit/885bbd7d0f6db843627986bf97d3f0db4cfddb02)

Good commits: 565
Total commits: 602

Good commits + 13 + 22 + 2 = 602

**Comment by algomaster99** [comment]
@khaes-kth I have 35 commits to analyze. Their reason for failure is documented in #83. But now, I will post if they can be fixed with a newer version of `MatchedLineFinder`.

**Comment by khaes-kth** [comment]
Thank you Aman!

Are the commits with the unkonwn problem also included here? I mean the bug where for some lines we couldn't add a breakpoint.

**Comment by algomaster99** [comment]
For patches where we could not add a breakpoint, we did not get any states or the file `sahab-left/right` was not created. All of those cases are analysed in the issue above.

**Comment by algomaster99** [comment]
See 6bf70cd6214303b773d2091b60e93ed0a52caea1, we could not find breakpoints initially for this patch. However, it is fixed after we rewrote the MLF.

**Comment by khaes-kth** [comment]
Awesome.

We'll discuss it tomorrow. I just want to make sure I am understanding the change and its effects correctly.

**Comment by algomaster99** [comment]
@khaes-kth The flaky behaviour is not fixed. See the build failure [here](https://github.com/algomaster99/collector-sahab/runs/7196863351?check_suite_focus=true#step:4:24542). This bug emanates from a bug in JDI, not collector-sahab.

You could send me a list of patches you think fail because of the same reason and I will try to find a trend among those patches. For example, if all of them have an offset of `2`, we could add a workaround in our tool to handle it.

**Comment by khaes-kth** [comment]
@algomaster99 I get an empty list of breakpoints and returns for the following commit id:
`20e5b8c28c217749dbba407416cae169df3c3`
Can you have a look?

**Comment by khaes-kth** [comment]
Reasons why we fail, after second run:
https://github.com/khaes-kth/PatchExplainer/issues/4#issuecomment-1204343078
